### ISSUE TITLE
How to access load balancer url from external server

### ISSUE THREAD

**Issue by EugeneFinch** [aws-solutions-library-samples/guidance-for-secure-blockchain-validation-using-aws-nitro-enclaves#7]
It appears the said deployment creates a private load balancer which is not accessible from a third-party server (not AWS). 
Is it possible to amend repository to make it possible to access it externally? 
currently a blocker for us.

**Comment by EugeneFinch** [comment]
here's the proof : 

<img width="1306" alt="Screen Shot 2023-10-29 at 5 25 13 PM" src="https://github.com/aws-samples/aws-nitro-enclave-blockchain-validator/assets/20620971/2dc3e07f-ba5c-4d66-9833-689bba40ae21">

**Comment by dpdornseifer** [comment]
Hi @EugeneFinch ,

the resources in the provided stack are all restricted to the VPC including DNS resolution via Rout53 private hosted zone.
There are different ways to extend such a solution, e.g. via reusing the same VPC and adapting the security groups.

The recommended way would be to create a VPC for all blockchain node related workloads and use VPC Private Link (https://aws.amazon.com/privatelink/) to connect these VPCs without having any information being exposed to pubic internet. You can then expose the required resources via security groups.

Let me know if that helps.
